### ISSUE TITLE
Containerização da aplicação

### ISSUE THREAD

**Issue by rafaelcanovas** [SunWK669/ACMEvita#1]
https://github.com/SunWK669/ACMEvita/blob/ae33920e1a28538819dbef96b3e0ebad2430d09f/docker-compose.yaml#L1-L13

Boa tarde Enzo, tudo bem?

Percebi que no seu `docker-compose` apenas containerizou o banco de dados. Como você faria para containerizar a aplicação?

Abs.

**Comment by SunWK669** [comment]
Boa tarde Rafael,

para containerizar a aplicação web seria necessário inclui-la no docker compose como um web service, especificando assim o local do buiild, porta a ser utilizada, variaveis de ambiente etc.

Seria necessário tambem criar um `Dockerfile` para o build da aplicação especificando o python 3.9 (que foi utilizado no desenvolvimento), instalar os requirements e executar o servidor.

Eu tambem inlcuiria o host `0.0.0.0` no `app.run` para que a aplicação pudesse ser acessada de fora do container

E por ultimo mas não menos importante, seria necessário alterar a variavel `DB_HOST` no `.env` de `localhost` para `db`, para que ela pudesse utilizar o serviço de banco de dados do docker-compose

**Comment by SunWK669** [comment]
Inclusive, como era uma alteração simples, subi um novo commit com a aplicação web containerizada caso queira dar uma olhada
