### ISSUE TITLE
Type-hints

### ISSUE THREAD

**Issue by rafaelcanovas** [SunWK669/ACMEvita#3]
https://github.com/SunWK669/ACMEvita/blob/ae33920e1a28538819dbef96b3e0ebad2430d09f/src/database/dao.py#L23

Boa tarde Enzo, tudo bem?

Percebi que neste arquivo essa é a unica linha com type-hints do Python, qual foi a motivação?

Quais benefícios os type-hints oferecem na aplicação e como podemos fazer com os type-hints sejam verificados e testados?

Abs.

**Comment by SunWK669** [comment]
A ideia inicial era utilizar type-hints em todos esses métodos visto que eles seriam ultilizados diversas vezes pelo código da API, auxiliando assim na documentação e otimização. Confesso que ai foi um erro meu, comecei a implemeta-los mas não os fiz em todos os métodos.

Creio que existam algumas vantagens no uso de type-hints, dentre elas:
- Servir como forma de documentação (Alguns editores de código apresentam a documentação da classe ou do método ao passar o mouse encima destes.)
- Auxiliam na otimização do código, uma vez que informações de tipos são muito importantes para otimizações em tempo de compilação

Com relação a verificação dos type-hints, poderiamos utilizar a biblioteca `mypy` ou o framework `fastapi`

**Comment by rafaelcanovas** [comment]
Obrigado Enzo!
